#!/bin/bash

project=$1
out_dir=$2
job_queue=$3


dependency_list=""

cd $project

for dir in *; do
	fastqc_out_dir=$(echo ${out_dir}/$dir)
	mkdir -p $fastqc_out_dir
	cd $dir;
		for fastq in *_R?_00?.fastq.gz; do
			echo `pwd` $fastq, $fastqc_out_dir
			jobid=$(sbatch -p $job_queue -o /dev/null -J rakeFASTQC --wrap "source ruby-2.3.1; rake -f ~/demultiplex_pipeline/run_analysis R1=$fastq output=$fastqc_out_dir" | awk '{print $4}')
			dependency_list=$(echo $jobid,$dependency_list)
			echo "Jobs submitted $jobid"
		done
	cd ..
done

cd $out_dir
jobid=$(sbatch -p $job_queue --wrap "sleep 3" | awk '{print $4}')
dependency_list=$(echo $dependency_list$jobid)
echo $dependency_list
sbatch -p $job_queue -o makefastqc.log --dependency=afterok:$dependency_list --wrap "bash ~/demultiplex_pipeline/make_fastqc_pdf.sh -p $out_dir -l fastqc_report.tex"

